# This file was generated by GoReleaser. DO NOT EDIT.
cask "llemme" do
  name "llemme"
  desc "Run local LLMs with llama.cpp and Hugging Face"
  homepage "https://github.com/nchapman/llemme"
  version "0.2.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llemme"

  on_macos do
    on_intel do
      url "https://github.com/nchapman/llemme/releases/download/v#{version}/llemme_#{version}_darwin_amd64.tar.gz"
      sha256 "b7e2968874a2bb146e49f6681820cd8326e101953b5b98d80f5b043c32cb65d2"
    end
    on_arm do
      url "https://github.com/nchapman/llemme/releases/download/v#{version}/llemme_#{version}_darwin_arm64.tar.gz"
      sha256 "52b246ca70f69807c16909f4f4b2e5e63abd28fbbae47852b20848690066a4c4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nchapman/llemme/releases/download/v#{version}/llemme_#{version}_linux_amd64.tar.gz"
      sha256 "ae8eaeb01b2f6efa908811004d66e89c1999a56bca0dc95c6463d21b23a601c3"
    end
    on_arm do
      url "https://github.com/nchapman/llemme/releases/download/v#{version}/llemme_#{version}_linux_arm64.tar.gz"
      sha256 "369fae8a646d451e0e649ed6b3dbd10cb227e12dd341736c1b7bf27b7e765d7a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/llemme"]
    end
  end

  # No zap stanza required
end
