# This file was generated by GoReleaser. DO NOT EDIT.
cask "llemme" do
  name "llemme"
  desc "Run local LLMs with llama.cpp and Hugging Face"
  homepage "https://github.com/nchapman/llemme"
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llemme"

  on_macos do
    on_intel do
      url "https://github.com/nchapman/llemme/releases/download/v#{version}/llemme_#{version}_darwin_amd64.tar.gz"
      sha256 "8bf1a66a96d55f94897a1d4183bbd13dff7d9e2e80dd230e60d687b63afc9316"
    end
    on_arm do
      url "https://github.com/nchapman/llemme/releases/download/v#{version}/llemme_#{version}_darwin_arm64.tar.gz"
      sha256 "301ba514fe19fb8f402c1aa1d46839ef2c03ceded24236b482153dff21804770"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nchapman/llemme/releases/download/v#{version}/llemme_#{version}_linux_amd64.tar.gz"
      sha256 "458f3e3b77b723a969a5dd1cd8f17a90cc8efc55fbdb7d40c04eb5aeb418045e"
    end
    on_arm do
      url "https://github.com/nchapman/llemme/releases/download/v#{version}/llemme_#{version}_linux_arm64.tar.gz"
      sha256 "e3cd2113a2ce95988ef0bce3fa180c68f328aad7a93ae1fa863686fbe5b83691"
    end
  end

  # No zap stanza required
end
