# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llemme < Formula
  desc "Run local LLMs with llama.cpp and Hugging Face"
  homepage "https://github.com/nchapman/llemme"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nchapman/llemme/releases/download/v0.2.5/llemme_0.2.5_darwin_amd64.tar.gz"
      sha256 "75727d83b9fecc3b7040c9f4cb7e3db3f05d409708a5111f72352d292c5acc01"

      def install
        bin.install "llemme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nchapman/llemme/releases/download/v0.2.5/llemme_0.2.5_darwin_arm64.tar.gz"
      sha256 "44afe14d644b900308c12fcad7f907c97a7db150e9ab715478fb953f90a62a62"

      def install
        bin.install "llemme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nchapman/llemme/releases/download/v0.2.5/llemme_0.2.5_linux_amd64.tar.gz"
      sha256 "9b35592a693d527f140da4376b1e1071762a84f6b8b939544455e17bfd85c449"
      def install
        bin.install "llemme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nchapman/llemme/releases/download/v0.2.5/llemme_0.2.5_linux_arm64.tar.gz"
      sha256 "4ba5776af5995df551c23765f3da43d8488f801a874cd9576659e8a893685de5"
      def install
        bin.install "llemme"
      end
    end
  end

  def post_install
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", bin/"llemme"
  end

  service do
    run [opt_bin/"llemme", "serve"]
    keep_alive crashed: true
    log_path var/"log/llemme.log"
    error_log_path var/"log/llemme.log"
  end
end
