# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lleme < Formula
  desc "Run local LLMs with llama.cpp and Hugging Face"
  homepage "https://github.com/nchapman/lleme"
  version "0.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nchapman/lleme/releases/download/v0.8.1/lleme_0.8.1_darwin_amd64.tar.gz"
      sha256 "f9dc88b10710723623c8cdd431a081b6cfce35a78f8fc65709867e8e6fb8c316"

      define_method(:install) do
        bin.install "lleme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nchapman/lleme/releases/download/v0.8.1/lleme_0.8.1_darwin_arm64.tar.gz"
      sha256 "e2350ef56d8c91dee014662d2da18ef4786b7d972e57a129d8dc7042ba2819bc"

      define_method(:install) do
        bin.install "lleme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nchapman/lleme/releases/download/v0.8.1/lleme_0.8.1_linux_amd64.tar.gz"
      sha256 "435cf483f27cf1858b18c21cefbddd70443b745cd1a49d7f7393d66246282e49"
      define_method(:install) do
        bin.install "lleme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nchapman/lleme/releases/download/v0.8.1/lleme_0.8.1_linux_arm64.tar.gz"
      sha256 "ae7c77af9f423335d806abfd6eec7c8f1db2dea1a2b6f8517a8fcdc02eeb607d"
      define_method(:install) do
        bin.install "lleme"
      end
    end
  end

  service do
    run [opt_bin/"lleme", "server", "start"]
    keep_alive crashed: true
    log_path var/"log/lleme.log"
    error_log_path var/"log/lleme.log"
  end
end
