# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llemme < Formula
  desc "Run local LLMs with llama.cpp and Hugging Face"
  homepage "https://github.com/nchapman/llemme"
  version "0.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nchapman/llemme/releases/download/v0.2.6/llemme_0.2.6_darwin_amd64.tar.gz"
      sha256 "6a97658dfc30cbbdb6ccd9cc0db14865516067d6f4091ee388005336e58e43f3"

      def install
        bin.install "llemme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nchapman/llemme/releases/download/v0.2.6/llemme_0.2.6_darwin_arm64.tar.gz"
      sha256 "9918cc2c69dbece9e76f50f67765fd6db6e0e23a643e0bf3c3a48fa20ef6fb4e"

      def install
        bin.install "llemme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nchapman/llemme/releases/download/v0.2.6/llemme_0.2.6_linux_amd64.tar.gz"
      sha256 "5073135002f505d543323ee977a2a0102c6822f1ef60cd4396b5c1f9780506c8"
      def install
        bin.install "llemme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nchapman/llemme/releases/download/v0.2.6/llemme_0.2.6_linux_arm64.tar.gz"
      sha256 "7ad89c42a1d8bcc6b01d8a08f5ea2c7b940b4b2504f6cf122c2f2609926f944c"
      def install
        bin.install "llemme"
      end
    end
  end

  service do
    run [opt_bin/"llemme", "serve"]
    keep_alive crashed: true
    log_path var/"log/llemme.log"
    error_log_path var/"log/llemme.log"
  end
end
