# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lleme < Formula
  desc "Run local LLMs with llama.cpp and Hugging Face"
  homepage "https://github.com/nchapman/lleme"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nchapman/lleme/releases/download/v0.5.0/lleme_0.5.0_darwin_amd64.tar.gz"
      sha256 "2304c50bf14962aca6a5d645caa0585e29a70e4670479e4cebd1967ac67f987d"

      def install
        bin.install "lleme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nchapman/lleme/releases/download/v0.5.0/lleme_0.5.0_darwin_arm64.tar.gz"
      sha256 "a700f6a3b19699d5896114a8c39c304de2b1fa90a1a5afd6bfacd9dd922e11e1"

      def install
        bin.install "lleme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nchapman/lleme/releases/download/v0.5.0/lleme_0.5.0_linux_amd64.tar.gz"
      sha256 "d29d2bd12d5e86ce116720e79ddf3a33e657ab6d01fd5969555ef2a74ac9e8c9"
      def install
        bin.install "lleme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nchapman/lleme/releases/download/v0.5.0/lleme_0.5.0_linux_arm64.tar.gz"
      sha256 "919303a5e594c0a5458781ed2a9543a7e5e51feb911e5175242b1598dc244fec"
      def install
        bin.install "lleme"
      end
    end
  end

  service do
    run [opt_bin/"lleme", "server", "start"]
    keep_alive crashed: true
    log_path var/"log/lleme.log"
    error_log_path var/"log/lleme.log"
  end
end
