# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lleme < Formula
  desc "Run local LLMs with llama.cpp and Hugging Face"
  homepage "https://github.com/nchapman/lleme"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nchapman/lleme/releases/download/v0.10.0/lleme_0.10.0_darwin_amd64.tar.gz"
      sha256 "be1964f32c3f5f9819ad5b77d871da156b94572097434821f61f323ae66fb560"

      define_method(:install) do
        bin.install "lleme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nchapman/lleme/releases/download/v0.10.0/lleme_0.10.0_darwin_arm64.tar.gz"
      sha256 "9cbb7b8cc9e50d8676aa8aa619aa857763054ecdd3142b7289a5ec2d6b632a0a"

      define_method(:install) do
        bin.install "lleme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nchapman/lleme/releases/download/v0.10.0/lleme_0.10.0_linux_amd64.tar.gz"
      sha256 "3461d28cc9f7d85aee6b63a723f74ce0ee547818b2536835b0d14c524086554a"
      define_method(:install) do
        bin.install "lleme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nchapman/lleme/releases/download/v0.10.0/lleme_0.10.0_linux_arm64.tar.gz"
      sha256 "eefc6150ac6fbe45ae61d883e6ffad0a967e78382d9400c98394105952148933"
      define_method(:install) do
        bin.install "lleme"
      end
    end
  end

  service do
    run [opt_bin/"lleme", "server", "start"]
    keep_alive crashed: true
    log_path var/"log/lleme.log"
    error_log_path var/"log/lleme.log"
  end
end
